---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check 
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # python syntax check of modules
  - python -m py_compile library/pcs_auth.py
  - python -m py_compile library/pcs_cluster.py
  - python -m py_compile library/pcs_constraint_colocation.py
  - python -m py_compile library/pcs_constraint_location.py
  - python -m py_compile library/pcs_constraint_order.py
  - python -m py_compile library/pcs_property.py
  - python -m py_compile library/pcs_resource.py
  - python -m py_compile library/pcs_resource_defaults.py

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
