---
- name: Configure firewalld
  when:
    - ansible_distribution in ['RedHat','CentOS','AlmaLinux','Rocky','Fedora']
    - not (ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6')
  block:
    - name: Enable and start firewalld service
      ansible.builtin.service:
        name: 'firewalld'
        enabled: true
        state: 'started'

    - name: Enable 'high-availability' firewalld service
      ansible.posix.firewalld:
        service: 'high-availability'
        permanent: true
        state: 'enabled'
        immediate: true

- name: Configure iptables (EL6)
  when:
    - ansible_distribution in ['RedHat']
    - ansible_distribution_major_version == '6'
  block:
    - name: Copy iptables configuration
      ansible.builtin.copy:
        src: 'iptables'
        dest: '/etc/sysconfig/iptables'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - Restart iptables

    - name: Enable and start iptables service
      ansible.builtin.service:
        name: 'iptables'
        enabled: true
        state: 'started'

    - name: Run handlers to reload iptables on system
      ansible.builtin.meta: flush_handlers
