---
- name: Configure HA-LVM ('clvm' type) and create shared VG and LV
  hosts: "{{target|default('cluster')}}"
  vars:
    # enable_repos: true      # RHEL-only
    # enable_eus_repos: false # RHEL-only
    local_vg_list:
      - 'vg_shared_c'
    clvm_vgs:
      - name: 'vg_shared_c'
        pvs: '/dev/sdb'
        lvs:
          - name: 'lv_name5'
            size: '200M'
  roles:
    - { role: 'ondrejhome.ha_cluster.lvm', HALVMtype: 'clvm' }
